displayName=Adventure Planner
author=WijheRP2023
description=Daily and weekly activities plus varied skilling tasks for diaries and maxing
tags=tasks,daily,weekly,diary,skilling,maxing,planner
plugins=com.adventureplanner.AdventurePlannerPlugin
version=0.1.1
build=standard
